CREATE TABLE SaleMstr(

[ComId] [varchar](20) NOT NULL default(''),
[AutoNo] [int] IDENTITY(1,1) NOT NULL,
[SID] [varchar](50) NOT NULL default(''),
[SDate] [datetime] NULL default(''),
[PartyCode] [varchar](50) NOT NULL default(''),
[PartyAutoNo] [int] NOT NULL default(''),
[TotalAmt] [money] NOT NULL default(0),
[Discount] [money] NOT NULL default(0),
[Payable] [money] NOT NULL default(0),
[Paid] [money] NOT NULL default(0),
[rmk] [varchar](150) NOT NULL default(''),
[ISBN] [int] NULL default(0),
[ESBN] [int] NULL default(0),
[VID] [varchar](50) NOT NULL default(''),
[VNo] [varchar](50) NOT NULL default(''),
[VAutoNo] [int] NOT NULL default(''),
[VType] [varchar](50) NOT NULL default(''),
[DriverName] [varchar](50) NOT NULL default(''),
[VDM] [varchar](50) NOT NULL default(''),
[AcPost] [varchar](50) NOT NULL default(''),
[AutoRmk] [varchar](50) NOT NULL default(''),
[Cur] [varchar](50) NOT NULL default(''),
[ComName] [varchar](150) NOT NULL default(''),
[PcName] [varchar](50) NOT NULL default(''),
[UserCode] [varchar](50) NOT NULL default(''),
[EntryTime] [datetime] NOT NULL default(GETDATE()),
[UserIP] [varchar](100) NOT NULL default(''),
[ISBAutoNo] [int] NOT NULL default(''),
[ESBAutoNo] [int] NOT NULL default(''),

);